const API_BASE = window.WAE_API_BASE || 'http://127.0.0.1:8000';
const token = new URLSearchParams(location.search).get('survey');
const $ = (id) => document.getElementById(id);
const state = { survey:null, guestOrigin:null };
const QUESTION_COPY = { cuisine:['What sounds good?','Pick up to two.','checkbox'], distance:['How far should we search?','Choose the maximum distance from the meetup spot.','range'], vibe:["What’s the vibe?",'Choose one.','radio'], price:['What’s the budget?','Per person, before drinks.','radio'], dietary:['Anything we should know?','Choose what the table should know.','checkbox'] };

function escapeHtml(value) { return String(value).replaceAll('&','&amp;').replaceAll('<','&lt;').replaceAll('>','&gt;').replaceAll('"','&quot;'); }
function prettyDate(value) { return new Intl.DateTimeFormat('en-US', { weekday:'long', month:'long', day:'numeric' }).format(new Date(`${value}T12:00:00`)); }
function prettyTime(value) { const [hours, minutes] = value.split(':'); return new Intl.DateTimeFormat('en-US', { hour:'numeric', minute:'2-digit' }).format(new Date(2000,0,1,Number(hours),Number(minutes))); }
function formatDistance(value) { const miles = Number(value); return Number.isFinite(miles) ? `${miles}${miles === 30 ? '+' : ''} mile${miles === 1 ? '' : 's'} from meetup` : value; }
function renderSchedule(availability) { return Object.entries(availability).map(([date,times]) => `<div class="survey-day"><h3>${escapeHtml(prettyDate(date))}</h3><div class="survey-choices">${times.map((time) => `<label class="survey-choice"><input type="checkbox" data-availability-date="${escapeHtml(date)}" value="${escapeHtml(time)}" /><span>${escapeHtml(prettyTime(time))}</span><b aria-hidden="true">✓</b></label>`).join('')}</div></div>`).join(''); }
function renderDistance(options) { const values = options.filter((option) => /^\d+$/.test(option)).map(String).sort((a,b) => Number(a)-Number(b)); if (values.length < 2) return ''; const initial = Math.min(3, values.length - 1); return `<div class="distance-control"><input type="range" min="0" max="${values.length - 1}" value="${initial}" data-distance-values="${values.join(',')}" aria-label="Maximum restaurant distance from meetup" /><output>${formatDistance(values[initial])}</output><input type="hidden" name="distance" value="${values[initial]}" /></div>`; }
function renderQuestions(questions) { $('survey-question-fields').innerHTML = Object.entries(questions || {}).filter(([,options]) => options?.length).map(([key,options]) => { const [title,help,type] = QUESTION_COPY[key] || [key,'Choose what works for you.','radio']; const controls = type === 'range' ? renderDistance(options) : options.map((option) => `<label class="survey-choice"><input ${type === 'radio' ? 'required' : ''} type="${type}" name="${escapeHtml(key)}" value="${escapeHtml(option)}" /><span>${escapeHtml(key === 'distance' ? formatDistance(option) : option)}</span><b aria-hidden="true">✓</b></label>`).join(''); return `<fieldset><legend>${escapeHtml(title)}</legend><p class="question-help">${escapeHtml(help)}</p><div class="survey-choices">${controls}</div></fieldset>`; }).join(''); }
function setupLocationPicker() { const input = $('guest-origin'); const menu = $('guest-origin-menu'); const status = $('location-status'); let timer; let sessionToken = crypto.randomUUID(); input.addEventListener('input', () => { state.guestOrigin = null; status.textContent = ''; clearTimeout(timer); menu.innerHTML = ''; menu.classList.add('hidden'); if (input.value.trim().length < 2) return; timer = setTimeout(async () => { try { const center = state.survey || {}; const query = new URLSearchParams({ input:input.value.trim(), cities_only:'false', session_token:sessionToken, radius_miles:'75' }); if (center.location_lat != null && center.location_lng != null) { query.set('near_lat', center.location_lat); query.set('near_lng', center.location_lng); } const response = await fetch(`${API_BASE}/api/locations/autocomplete?${query}`); if (!response.ok) throw new Error(); const data = await response.json(); menu.innerHTML = (data.predictions || []).map((item) => `<button type="button" class="location-option" role="option" data-place-id="${escapeHtml(item.place_id)}" data-label="${escapeHtml(item.text)}"><strong>${escapeHtml(item.main_text || item.text)}</strong><span>${escapeHtml(item.secondary_text || '')}</span></button>`).join(''); menu.classList.toggle('hidden', !menu.children.length); } catch { status.textContent = 'Location suggestions are unavailable. You can leave this blank.'; } },250); }); menu.addEventListener('click', async (event) => { const option = event.target.closest('.location-option'); if (!option) return; try { const center = state.survey || {}; const response = await fetch(`${API_BASE}/api/locations/details`, { method:'POST', headers:{'Content-Type':'application/json'}, body:JSON.stringify({ place_id:option.dataset.placeId, session_token:sessionToken, near_lat:center.location_lat ?? null, near_lng:center.location_lng ?? null, radius_miles:75 }) }); if (!response.ok) { if (response.status === 422) status.textContent = 'Choose a place within 75 miles of the meetup city.'; throw new Error(); } const details = await response.json(); state.guestOrigin = details; input.value = details.label || option.dataset.label; status.textContent = 'Location noted'; menu.classList.add('hidden'); sessionToken = crypto.randomUUID(); } catch { if (!status.textContent) status.textContent = 'Could not verify that place. You can leave this blank.'; } }); document.addEventListener('click', (event) => { if (!event.target.closest('.location-picker')) menu.classList.add('hidden'); }); }
async function loadSurvey() { if (!token) return; const response = await fetch(`${API_BASE}/api/surveys/${token}`); const data = await response.json().catch(() => ({})); if (!response.ok) { $('survey-title').textContent = 'Invitation not found.'; $('survey-location').textContent = data.detail || 'This guest link is no longer available.'; $('survey-form').classList.add('hidden'); return; } state.survey = data; $('survey-title').innerHTML = `Help pick <em>${escapeHtml(data.event_name)}.</em>`; $('survey-location').textContent = `${data.location} · about 30 seconds · no sign-up`; if (data.is_open === false) { $('survey-form').classList.add('hidden'); $('survey-closed').classList.remove('hidden'); return; } renderQuestions(data.questions); $('survey-schedule').innerHTML = renderSchedule(data.availability || Object.fromEntries((data.dates || []).map((date) => [date,data.times || []]))); }
$('survey-question-fields').addEventListener('input', (event) => { if (!event.target.matches('input[type="range"][data-distance-values]')) return; const values = event.target.dataset.distanceValues.split(','); event.target.parentElement.querySelector('output').textContent = formatDistance(values[Number(event.target.value)]); event.target.parentElement.querySelector('input[type="hidden"]').value = values[Number(event.target.value)]; });
$('survey-form').addEventListener('change', (event) => { if (event.target.name === 'cuisine' && document.querySelectorAll('input[name="cuisine"]:checked').length > 2) event.target.checked = false; });
$('survey-form').addEventListener('submit', async (event) => { event.preventDefault(); if (!state.survey) return; $('form-error').textContent = ''; const availability = {}; document.querySelectorAll('[data-availability-date]:checked').forEach((input) => { (availability[input.dataset.availabilityDate] ||= []).push(input.value); }); const dates = Object.keys(availability); const times = [...new Set(Object.values(availability).flat())]; if (!dates.length || !times.length) { $('form-error').textContent = 'Choose at least one date and time.'; return; } const origin = state.guestOrigin || {}; const answer = { dates, times, availability, cuisines:[...document.querySelectorAll('input[name="cuisine"]:checked')].map((input) => input.value), dietary:[...document.querySelectorAll('input[name="dietary"]:checked')].map((input) => input.value), distance:document.querySelector('input[name="distance"]')?.value, vibe:document.querySelector('input[name="vibe"]:checked')?.value, price:document.querySelector('input[name="price"]:checked')?.value, origin_place_id:origin.place_id || null, origin_label:origin.label || null, origin_lat:origin.latitude ?? null, origin_lng:origin.longitude ?? null, respondent_token:localStorage.getItem('respondentToken') || crypto.randomUUID() }; const button = event.target.querySelector('.submit-button'); button.disabled = true; button.textContent = 'Saving your picks…'; try { const response = await fetch(`${API_BASE}/api/surveys/${token}/responses`, { method:'POST', headers:{'Content-Type':'application/json'}, body:JSON.stringify(answer) }); if (response.status === 410) { $('survey-form').classList.add('hidden'); $('survey-closed').classList.remove('hidden'); return; } if (!response.ok) { const data = await response.json().catch(() => ({})); throw new Error(data.detail || 'Could not save your response.'); } localStorage.setItem('respondentToken', answer.respondent_token); $('survey-form').classList.add('hidden'); $('survey-thanks').classList.remove('hidden'); } catch (error) { $('form-error').textContent = error instanceof Error ? error.message : 'Could not save your response. Please try again.'; button.disabled = false; button.innerHTML = 'Send my picks <span aria-hidden="true">→</span>'; } });
setupLocationPicker(); loadSurvey();
